mysite/urls.py
from django.contrib import admin
from django.urls import path

from app01 import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('index/', views.index),
    # path('layout/', views.layout),
    path('admin/individual_user/', views.admin_individual),
    path('admin/individual_user/<int:nid>/view_all/', views.admin_individual_view_all),
    path('admin/individual_user/<int:nid>/edit/', views.admin_individual_edit),
    path('admin/individual_user/add/', views.admin_add_individual),
    path('admin/individual_user/<int:nid>/delete/', views.admin_individual_delete),


    path('admin/corporate_user/', views.admin_corporate),
    path('admin/corporate_user/add/', views.admin_corporate_add),
    path('admin/corporate_user/<int:nid>/view_all/', views.admin_corporate_view_all),
    path('admin/corporate_user/<int:nid>/edit/', views.admin_corporate_edit),
    path('admin/corporate_user/<int:nid>/delete/', views.admin_corporate_delete),

    path('image/code/', views.image_code),


    path('admin/add/', views.admin_add),
    path('admin/login/', views.admin_login),
    path('admin/logout/', views.admin_logout),

    path('admin/office/', views.office_show),
    path('admin/office/add/', views.office_add),
    path('admin/office/<int:nid>/edit/', views.office_edit),
    path('admin/office/<int:nid>/delete/', views.office_delete),

    path('user/individual/', views.individual)

]

app01/models.py
import dateutil.utils
from django.db import models
from datetime import datetime
from random import random, randint

# Create your models here.
# for database


class AdminInfo(models.Model):
    name = models.CharField(max_length=32)
    password = models.CharField(max_length=64)


class IndividualInfo(models.Model):
    username = models.CharField(verbose_name="username", max_length=32,
                                default=(datetime.strftime(datetime.now(), '%Y%m%d%H%M')) + str(randint(1000, 9999)))
    password = models.CharField(verbose_name="password", max_length=64,
                                default=(datetime.strftime(datetime.now(), '%Y%m%d%H%M')) + str(randint(1000, 9999)))
    street = models.CharField(verbose_name="street", max_length=64)
    city = models.CharField(verbose_name="city", max_length=32)
    zipcode = models.CharField(verbose_name="zipcode", max_length=10)
    email = models.CharField(verbose_name="e-mail address", max_length=32)
    phone = models.CharField(verbose_name="phone number", max_length=32)
    FirstName = models.CharField(verbose_name="first name", max_length=32)
    MiddleName = models.CharField(verbose_name="middle name", max_length=32)
    LastName = models.CharField(verbose_name="last name", max_length=32)
    InsuranceCompany = models.CharField(verbose_name="insurance company", max_length=32)
    InsuranceNumber = models.CharField(verbose_name="insurance number", max_length=10)
    rate = models.DecimalField(verbose_name="Coupon Rate", max_digits=10, decimal_places=2, default=0)
    StartDate = models.DateField(verbose_name="Start Date")
    EndDate = models.DateField(verbose_name="End Date")


class CorporationUser(models.Model):
    street = models.CharField(verbose_name="street", max_length=64)
    city = models.CharField(verbose_name="city", max_length=32)
    zipcode = models.CharField(verbose_name="zipcode", max_length=10)
    email = models.CharField(verbose_name="e-mail address", max_length=32)
    phone = models.CharField(verbose_name="phone number", max_length=32)
    employ_id = models.CharField(verbose_name="employ id", max_length=10)
    corporation_choices = (
        (1, "D&G Tax Law"),
        (2, "The Acrobatic Accountants LLC"),
        (3, "Cafe Msica"),
        (4, "Artisan Recording"),
        (5, "New York Man"),
        (6, "Dreamlike Moustaches"),
        (7, "Swift River Sports"),
        (8, "The Big Apple Cocktail Company"),
        (9, "Pouring Palaces"),
        (10, "Schmalzy Pet"),
    )
    corporation_name = models.SmallIntegerField(verbose_name="corporation name", choices=corporation_choices)
    rate = models.DecimalField(verbose_name="Coupon Rate", max_digits=10, decimal_places=2, default=0)


class Admin(models.Model):
    username = models.CharField(verbose_name="user name", max_length=32)
    password = models.CharField(verbose_name="password", max_length=64)


class Office(models.Model):
    name = models.CharField(verbose_name="office name", max_length=64)
    street = models.CharField(verbose_name="street", max_length=64)
    city = models.CharField(verbose_name="city",max_length=32)
    zipcode = models.CharField(verbose_name="zipcode", max_length=10)
    phone = models.CharField(verbose_name="phone number", max_length=10)

app01/views.py
from django.shortcuts import render, HttpResponse, redirect
from app01 import models
from app01.utils.pagination import Pagination
from app01.utils.form import AdminIndividualFormViewAll, AdminIndividualEdit, AdminIndividualAdd, AdminCorporateAdd, \
    AdminCorporateViewAll, AdminCorporateEdit, AdminAdd, AdminLogin, OfficeAdd, OfficeEdit

from app01.utils.code import check_code
from io import BytesIO


# Create your views here.


def admin_individual(request):
    data_dict = {}
    search_data = request.GET.get('q', "")
    if search_data:
        data_dict["id"] = search_data

    queryset = models.IndividualInfo.objects.filter(**data_dict)

    page_object = Pagination(request, queryset, page_size=5)
    context = {
        "queryset": page_object.page_queryset,
        "page_string": page_object.html(),
    }
    return render(request, 'admin_individual.html', context)


def admin_individual_view_all(request, nid):
    row_object = models.IndividualInfo.objects.filter(id=nid).first()
    form = AdminIndividualFormViewAll(instance=row_object)
    return render(request, 'admin_view_all.html', {'form': form})


def admin_individual_edit(request, nid):
    row_object = models.IndividualInfo.objects.filter(id=nid).first()

    # get the data from the database for edit
    if request.method == 'GET':
        form = AdminIndividualEdit(instance=row_object)
        return render(request, 'admin_edit.html', {'form': form})
    form = AdminIndividualEdit(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/admin/individual_user/')
    return render(request, 'admin_edit.html', {'form': form})


def admin_add_individual(request):
    if request.method == 'GET':
        form = AdminIndividualAdd()
        return render(request, 'admin_add_individual.html', {'form': form})
    form = AdminIndividualAdd(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/admin/individual_user/')
    return render(request, 'admin_add_individual.html', {'form': form})


def admin_individual_delete(request, nid):
    models.IndividualInfo.objects.filter(id=nid).delete()
    return redirect('/admin/individual_user/')


def admin_corporate(request):
    data_dict = {}
    search_data = request.GET.get('q', "")
    if search_data:
        data_dict["employ_id"] = search_data

    queryset = models.CorporationUser.objects.filter(**data_dict)
    page_object = Pagination(request, queryset, page_size=5)
    context = {
        "queryset": page_object.page_queryset,
        "page_string": page_object.html(),
    }
    return render(request, 'admin_corporate.html', context)


def admin_corporate_add(request):
    if request.method == 'GET':
        form = AdminCorporateAdd()
        return render(request, 'admin_add_corporate.html', {'form': form})
    form = AdminCorporateAdd(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/admin/corporate_user/')
    return render(request, 'admin_add_corporate.html', {'form': form})


def admin_corporate_view_all(request, nid):
    row_object = models.CorporationUser.objects.filter(id=nid).first()
    form = AdminCorporateViewAll(instance=row_object)
    return render(request, 'admin_corporate_view_all.html', {'form': form})


def admin_corporate_edit(request, nid):
    row_object = models.CorporationUser.objects.filter(id=nid).first()

    # get the data from the database for edit
    if request.method == 'GET':
        form = AdminCorporateEdit(instance=row_object)
        return render(request, 'admin_corporate_edit.html', {'form': form})

    form = AdminCorporateEdit(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/admin/corporate_user/')
    return render(request, 'admin_corporate_edit.html', {'form': form})


def admin_corporate_delete(request, nid):
    models.CorporationUser.objects.filter(id=nid).delete()
    return redirect('/admin/corporate_user/')


def admin_add(request):
    if request.method == 'GET':
        form = AdminAdd()
        return render(request, 'admin_add.html', {'form': form})

    form = AdminAdd(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/admin/login/')
    return render(request, 'admin_add.html', {'form': form})


def admin_login(request):
    if request.method == 'GET':
        form = AdminLogin()
        return render(request, 'admin_login.html', {'form': form})
    form = AdminLogin(data=request.POST)
    if form.is_valid():
        user_input_code = form.cleaned_data.pop('code')
        code = request.session.get('image_code', "")
        if code.upper() != user_input_code.upper():
            form.add_error("code", "Wrong Code")
            return render(request, 'admin_login.html', {'form': form})

        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            form.add_error("password", "Wrong Username or Password")
            return render(request, 'admin_login.html', {'form': form})
        request.session["info"] = {'id': admin_object.id, 'name': admin_object.username}
        request.session.set_expiry(60 * 60 * 24 * 7)
        return redirect("/admin/individual_user/")
    return render(request, 'admin_login.html', {'form': form})


def image_code(request):
    img, code_string = check_code()
    request.session['image_code'] = code_string
    # request.session.set_expiry(60)

    stream = BytesIO()
    img.save(stream, 'png')
    return HttpResponse(stream.getvalue())


def admin_logout(request):
    request.session.clear()
    return redirect('/admin/login/')


def office_show(request):
    data_dict = {}
    search_data = request.GET.get('q', "")
    if search_data:
        data_dict["id"] = search_data

    queryset = models.Office.objects.filter(**data_dict)

    page_object = Pagination(request, queryset, page_size=5)
    context = {
        "queryset": page_object.page_queryset,
        "page_string": page_object.html(),
    }
    return render(request, 'admin_office.html', context)


def office_add(request):
    if request.method == 'GET':
        form = OfficeAdd()
        return render(request, 'office_add.html', {'form': form})

    form = OfficeAdd(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/admin/office/')
    return render(request, 'office_add.html', {'form': form})


def office_edit(request, nid):
    row_object = models.Office.objects.filter(id=nid).first()

    # get the data from the database for edit
    if request.method == 'GET':
        form = OfficeEdit(instance=row_object)
        return render(request, 'office_edit.html', {'form': form})
    form = OfficeEdit(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/admin/office/')
    return render(request, 'office_edit.html', {'form': form})


def office_delete(request, nid):
    models.Office.objects.filter(id=nid).delete()
    return redirect('/admin/office/')


def individual(request):
    return render(request, 'individual.html')


app01/templates/admin_add.html
{% extends 'login_template.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> Add Admin </h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}


app01/templates/admin_add_corporate.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> Add Corporate User </h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}


app01/templates/admin_add_individual.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> Add Individual User </h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script>
        $(function () {
            $('#id_StartDate').datepicker({
                format: 'yyyy-mm-dd',
                endDate: '0',
                autoclose: true
            });

            $('#id_EndDate').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '0',
                autoclose: true
            });
        })
    </script>
{% endblock %}

app01/templates/admin_corporate.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/admin/corporate_user/add">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                Add One
            </a>

            <div style="float: right;width: 300px;">
                <form method="get">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search for..."
                               value="{{ search_data }}">
                        <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                      </span>
                    </div>
                </form>
            </div>

        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                User List
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Corporation Name</th>
                    <th>Employ ID</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Rate</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th>{{ obj.get_corporation_name_display }}</th>
                        <td>{{ obj.employ_id}}</td>
                        <td>{{ obj.email }}</td>
                        <td>{{ obj.phone }}</td>
                        <td>{{ obj.rate }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/admin/corporate_user/{{ obj.id }}/view_all/">View All</a>
                            <a class="btn btn-primary btn-xs" href="/admin/corporate_user/{{ obj.id }}/edit/">Edit</a>
                            <a class="btn btn-danger btn-xs" href="/admin/corporate_user/{{ obj.id }}/delete/">Delete</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>

        <ul class="pagination" style="margin-left: 300px">
            {{ page_string }}
        </ul>
    </div>
{% endblock %}

app01/templates/admin_corporate_edit.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> Edit Corporate User </h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script>
        $(function () {
            $('#id_StartDate').datepicker({
                format: 'yyyy-mm-dd',
                endDate: '0',
                autoclose: true
            });

            $('#id_EndDate').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '0',
                autoclose: true
            });
        })
    </script>
{% endblock %}

app01/templates/admin_corporate_view_all.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> Detailed Information </h3>
            </div>
            <div class="panel-body">

                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

app01/templates/admin_edit.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> Edit Individual User </h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script>
        $(function () {
            $('#id_StartDate').datepicker({
                format: 'yyyy-mm-dd',
                endDate: '0',
                autoclose: true
            });

            $('#id_EndDate').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '0',
                autoclose: true
            });
        })
    </script>
{% endblock %}

app01/templates/admin_individual.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/admin/individual_user/add">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                Add One
            </a>

            <div style="float: right;width: 300px;">
                <form method="get">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search for..."
                               value="{{ search_data }}">
                        <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                      </span>
                    </div>
                </form>
            </div>

        </div>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                User List
            </div>


            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>First Name</th>
                    <th>Middle Name</th>
                    <th>Last Name</th>
                    <th>Street</th>
                    <th>City</th>
                    <th>Zipcode</th>
                    <th>Phone Number</th>
                    <th>Email</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.FirstName}}</td>
                        <td>{{ obj.MiddleName }}</td>
                        <td>{{ obj.LastName }}</td>
                        <td>{{ obj.street }}</td>
                        <td>{{ obj.city }}</td>
                        <td>{{ obj.zipcode}}</td>
                        <td>{{ obj.phone }}</td>
                        <td>{{ obj.email }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/admin/individual_user/{{ obj.id }}/view_all/">View All</a>
                            <a class="btn btn-primary btn-xs" href="/admin/individual_user/{{ obj.id }}/edit/">Edit</a>
                            <a class="btn btn-danger btn-xs" href="/admin/individual_user/{{ obj.id }}/delete/">Delete</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>

        <ul class="pagination" style="margin-left: 300px">
            {{ page_string }}
        </ul>
    </div>
{% endblock %}

app01/templates/admin_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="account">
    <h2>Admin Login</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label>Username</label>
            {{ form.username }}
            <span style="color: red;">{{ form.username.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>Password</label>
            {{ form.password }}
            <span style="color: red;">{{ form.password.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label for="id_code">CAPTCHA</label>
            <div class="row">
                <div class="col-xs-7">
                    {{ form.code }}
                    <span style="color: red;">{{ form.code.errors.0 }}</span>
                </div>
                <div class="col-xs-5">
                    <img id="image_code" src="/image/code/" style="width: 125px;">
                </div>
            </div>
        </div>
        <a class="btn btn-primary" href="/admin/add/"> Register </a>
        <input type="submit" value="Submit" class="btn btn-primary">
    </form>
</div>

</body>
</html>

app01/templates/admin_view_all.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> Detailed Information </h3>
            </div>
            <div class="panel-body">

                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

app01/templates/office_add.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> Add Individual User </h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script>
        $(function () {
            $('#id_StartDate').datepicker({
                format: 'yyyy-mm-dd',
                endDate: '0',
                autoclose: true
            });

            $('#id_EndDate').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '0',
                autoclose: true
            });
        })
    </script>
{% endblock %}